# Generated by Django 3.2 on 2021-07-30 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_auto_20210729_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quizapplication',
        ),
    ]
