# Generated by Django 3.2 on 2021-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_delete_quizapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='looping',
            name='correct_ans',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='looping',
            name='option1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='looping',
            name='option2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='looping',
            name='option3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='looping',
            name='option4',
            field=models.TextField(),
        ),
    ]
