# Generated by Django 3.2 on 2021-08-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_auto_20210801_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='oops',
            new_name='ExceptionHandling',
        ),
    ]
